### ISSUE TITLE
Improperly licensed content from World Models library

### ISSUE THREAD

**Issue by d41k4n** [32kda/osm2xp#15]
Since assets from World Models library are included (either modified or verbatim) their [GNU GPL 3.0 license conditions](https://github.com/d41k4n/world-models/blob/0.8.0/LICENSE) have to be respected.

Examples of improperly licensed assets:
https://github.com/32kda/osm2xp/blob/master/osm2xp_additions/xplane/objects/GSM-tow-50m.obj
https://github.com/32kda/osm2xp/blob/master/osm2xp_additions/xplane/objects/R_Tower_50m.obj

Originals:
https://github.com/d41k4n/world-models/blob/0.8.0/obstacles/GSM-tow.obj
https://github.com/d41k4n/world-models/blob/0.8.0/obstacles/R_Tower_50m.obj

To solve this the project including all of its distribution formats would have to fulfill the following conditions:

1. License and copyright notice
2. State changes
3. Disclose source
4. Same license

**Comment by 32kda** [comment]
Sorry, didn't got, what a problem is. OSM2XP is also GPL 3.0 (https://sourceforge.net/projects/osm2xp/) and it's source is accessible here.

What else needs to be done?

**Comment by d41k4n** [comment]
I would suggest putting a LICENSE file with the content of the GNU GPL 3.0 terms into the root folder of both this repository and the binary releases.

I would also state somewhere obvious (like in the README.md) the source where you obtained the assets.

And if you modified them in any way provide information on the changes.

**Comment by 32kda** [comment]
Added given info to repo root. Will add to binary build in next release.

**Comment by 32kda** [comment]
GPL 3 text file annd README with assets notes added to release 4.2.0

**Comment by 32kda** [comment]
Closing
