### ISSUE TITLE
DSFTool binaries are outdated

### ISSUE THREAD

**Issue by d41k4n** [32kda/osm2xp#16]
Newer DSFTool 64bit binaries for all platforms are available here:
https://forums.x-plane.org/index.php?/forums/topic/175068-dsftool-64bit-binaries/

**Comment by BigKananga** [comment]
The ones included in v4.6.2 are the current final ones from 2015.

Here is the more or less official beta version (linking also to the thread mentioned above):
https://developer.x-plane.com/2020/09/command-line-tools-beta-builds/

**Comment by 32kda** [comment]
Closing for now, if so. Please reopen if needed.
