### ISSUE TITLE
Questions about Models porvided

### ISSUE THREAD

**Issue by SunnyCommunications** [32kda/osm2xp#21]
I came across this repo the other night and wanted to make sure that I could use it for my needs. I know OSM I'm able to use though its the models/facade. The GNU v3.0 does allow me to use your program for commercial use. Though I wanted to make sure that all models you have added are also allowed to. If not is there a way for me to go into the source and remove those that do not allow use for commercial use?

Please note its not use for selling the maps I build with it, its for a business I'm helping build out their visual library for.

**Comment by 32kda** [comment]
Hello. AFAIR all the stuff in it is GPL or maybe some other "friendly"
license, so you can use it even for commercial projects. Anyway, personally
I would not complain in any case, feel free to do whatever you want)

BR, Dmitry

сб, 26 февр. 2022 г., 21:11 SunnyCommunications ***@***.***>:

**Comment by SunnyCommunications** [comment]
Thanks for the info.
