### ISSUE TITLE
Using SFD Global buildings instead of facades

### ISSUE THREAD

**Issue by GiacomoLaw** [32kda/osm2xp#22]
Awesome app, thanks so much. Is there a way I can use the SFD Global autogen instead of the default facades?

Thanks

**Comment by 32kda** [comment]
You're welcome)

Unfortunately I know nothing about that, where can I read about it? Facades was choosed initially since it's simpliest way to generate any contours from OSM map.

**Comment by GiacomoLaw** [comment]
SFD Global is autogen rather than facades - it's its own custom scenery package so I was just wondering whether I could tell OSM2XP to use autogen rather than facades? Thanks

**Comment by BigKananga** [comment]
@GiacomoLaw 
You'll have to use the virtual paths of SFD Global. You'll find them in SFD Globals library.txt.
If you want to use objects instead of facades you'll have to use 3D Objects option instead of Building facades option.

**Comment by GiacomoLaw** [comment]
> @GiacomoLaw You'll have to use the virtual paths of SFD Global. You'll find them in SFD Globals library.txt. If you want to use objects instead of facades you'll have to use 3D Objects option instead of Building facades option.

Excellent thank you! Where do I do this thing with the virtual paths of SFD?
