### ISSUE TITLE
.for for scrub class

### ISSUE THREAD

**Issue by GiacomoLaw** [32kda/osm2xp#23]
Any chance to include a .for to use for the scrub class on osm?

Using the Terraflora one and makes a significant difference.

However, it seems to be placed even over roads. Is there a way to fix this?

Thanks!

**Comment by 32kda** [comment]
Hello!
You can add any .for files to your autogens, they can be tuned on the tab shown below

Please attach some sample osm where you see a problem with brushes/trees, or just give a line ID, so I can download pbf file for it myself.

Unfortunately now I have pretty few time for this work, but maybe I'll find some to fix it.

![изображение](https://user-images.githubusercontent.com/820526/163910482-52881c1f-d1ab-4359-841c-efb5674db2f3.png)

**Comment by 32kda** [comment]
Also, where can I get the Terraflora one?

**Comment by GiacomoLaw** [comment]
You need to own Terraflora from orbx - I used the shrubs_hot.for, and you need the broad_coni_shrb.dds.

Just have this suggestion for those who don't have Terraflora - some small shrubbery included would be great as it really makes a difference in scenery look.

![image](https://user-images.githubusercontent.com/9038673/163965549-40a89f78-a7e2-476f-95b9-9c0fce2b50cc.png)

Cheers!

**Comment by BigKananga** [comment]
@GiacomoLaw 
You'll have to use the virtual paths of Terraflora. You'll find them in Terrafloras library.txt.

**Comment by GiacomoLaw** [comment]
> @GiacomoLaw You'll have to use the virtual paths of Terraflora. You'll find them in Terrafloras library.txt.

Yep, got it working fine. This is just a request for a .for file for shrubs to be added to the default library itself.

**Comment by BigKananga** [comment]
> This is just a request for a .for file for shrubs to be added to the default library itself.

Yes, the default config could be optimized. landuse=orchard and maybe natural=tree_row would be also a useful addition.

**Comment by 32kda** [comment]
Unfortunately I have no time to search for suitable .for files myself atm. If there're something suitable in opensource libs - please give me a link, I'll update a 4.6.x and 5.x streams to include given rules.

**Comment by GiacomoLaw** [comment]
https://www.opensceneryx.com/forests/trees/usa/arizona_new_mexico/shrub/

OpensceneryX appears to have some .for type shrubs

**Comment by BigKananga** [comment]
This one seems to be better, more dense:
https://www.opensceneryx.com/forests/trees/europe/alpine/shrub/

**Comment by 32kda** [comment]
Thanks alot, I'll try to add it and publish in nearest future
