### ISSUE TITLE
Linux version request

### ISSUE THREAD

**Issue by soitanen** [32kda/osm2xp#8]
Requesting for Ubuntu-compatible version or instructions about running this utility.

**Comment by 32kda** [comment]
This would require additional work.
I have it in plans but unfortunately can't provide exact schedule for now.

**Comment by soitanen** [comment]
Без проблем, буду ждать.

**Comment by 32kda** [comment]
Заходите на https://sourceforge.net/projects/osm2xp/upload/
Там я выложил версии для x86 и x64. По результатам можете написать мне ЛС на форуме, наверное так будет удобнее.

**Comment by s7relok** [comment]
Addition to the interest of a linux version

**Comment by 32kda** [comment]
Working on next version of this utility currently. Will try to provide Linux version working "out of the box".

**Comment by 32kda** [comment]
Linux version is finally available, for both 3.5.1 and 4.0.0.

Please open separate bugs for problems with it
