### ISSUE TITLE
ОСМ данные для генерации классов ландшафта [Draped polygons support]

### ISSUE THREAD

**Issue by soitanen** [32kda/osm2xp#9]
можно ли генерировать draped polygons на основании ОСМ данных? Типа парковка - асфальт. Лужайка - трава. Лес - кроме самих деревьев еще и подложку леса, ну и прочее. Чтобы на автогенных территориях (без фотоподложек) достойно смотрелось все сгенерированное

**Comment by 32kda** [comment]
Добавлено в 4.0.0
Supported in 4.0.0
